### ISSUE TITLE
wow thats fast

### ISSUE THREAD

**Issue by danday74** [lborgav/is-prime#2]
Hey thanks for this package, this is MUCH faster than anything else available.

I checked it from 1 to 104395301 and was 100% accurate.

Where did you get the algorithm from in https://github.com/lborgav/is-prime/blob/master/index.js ?

Does this algorithm fail to be accurate at larger numbers? If so, what is the failure point?

Is there any way to determine what prime number it is? For example, instead of ...
```
isPrime(11) // returns true
isPrime(12) // returns false
```
to do ...
```
isPrime(11) // returns 5, being the 5th prime number
isPrime(12) // returns false
```

Many thanks for publishing this :) Very impressed

**Comment by lborgav** [comment]
Hey @danday74 

Sorry for the late response. This algorithm is a well-known optimization and there a are lot of references like this one in [wikipedia](https://en.wikipedia.org/wiki/Primality_test) and some answers on StackOverflow. I just implemented it as a npm module
